easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          # ... autres champs ...
          - {
              property: "roles",
              type: "choice",
              type_options:
                {
                  multiple: true,
                  choices: { "User": "ROLE_USER", "Admin": "ROLE_ADMIN" },
                },
            }
