security:
  # Hashers configuration
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: argon2id

  # Roles hierarchy
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  # User providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  # Firewall settings
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: login
        check_path: login
        enable_csrf: true
        default_target_path: "/" # This will redirect to homepage after login

      custom_authenticator: App\Security\AppAuthenticator
      entry_point: App\Security\AppAuthenticator

      logout:
        path: app_logout
        target: "/" # This will redirect to homepage after logout

  # Access control settings
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: argon2id
        cost: 4
        time_cost: 3
        memory_cost: 10
