security:
  # Hashers configuration
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # User providers
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  # Firewall settings
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider

      # You might have form_login & custom authenticator here, just as an example
      form_login:
        login_path: login
        check_path: login
        enable_csrf: true

      # Here is how you set your custom authenticator
      custom_authenticator: App\Security\AppAuthenticator

      # Set entry_point
      entry_point: App\Security\AppAuthenticator

      logout:
        path: app_logout
        target: "/"

  # Access control settings
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
